version: '3.9'

services:
  cassandra-service:
    image: cassandra:4.0
    ports:
      - "9042:9042"
    volumes:
      - cassandra-volume:/var/lib/cassandra
    networks:
      - ms-network
  zanger-client-web-service:
    image: zanger-web:latest
    restart: always
    ports:
      - "80:80"
    environment:
      BACKEND_URL: ws://zanger-messages-service:8080
    depends_on: 
      zanger-messages-service:
        condition: service_started
    networks:
      - ms-network
  zanger-messages-service:
    image: zanger-messages:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      CASSANDRA_CONNECTION_URL: cassandra-service
      BOT_FIRST_MESSAGE: |
        Здравствуйте! 
        Меня зовут Зангер, и я здесь, чтобы помочь вам с юридическими вопросами. 
        Что именно вас интересует сегодня?
    depends_on:
      cassandra-service:
        condition: service_started
    networks:
      - ms-network

volumes:
  cassandra-volume:

networks:
  ms-network:
    driver: bridge
