version: '3.9'

services:
  cassandra-service:
    image: cassandra:4.0
    ports:
      - "9042:9042"
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=300M
    volumes:
      - cassandra-volume:/var/lib/cassandra
    networks:
      - ms-network

volumes:
  cassandra-volume:

networks:
  ms-network:
    driver: bridge
