version: '3.9'

services:
  cassandra-service:
    image: cassandra:4.0
    ports:
      - "9042:9042"
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=740M
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge
